config/routes.rb
Rails.application.routes.draw do
  resources :categories, except: :show
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index
   resources :products, path: '/'

   namespace :authentication, path: '', as: '' do 
     resources :users, only: [:new ,:create]  
   end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :products, dependent: :restrict_with_exception
end

app/models/product.rb
class Product < ApplicationRecord
  include PgSearch::Model

  pg_search_scope :search_full_text, against:{
  title: 'A',
  description: 'B'
  }
  ORDER_BY={
    newest: "created_at DESC",
    expensive: "price DESC",
    cheapest: "price ASC"
  }
  has_one_attached :photo
  validates :title,presence: true
  validates :description,presence: true
  validates :price,presence: true

  belongs_to :category
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  validates :email, presence: true, uniqueness: true,
 format: {
      with: /\A([\w+\-].?)+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i,
      message: :invalid
    }

  validates :username, presence: true, uniqueness: true,
  length: { in: 3..15 },
  format: {
    with: /\A[a-z-0-9-A-Z]+\z/,
    message: :invalid
  }
  validates  :password, length: { minimum: 6}

  before_save :downcase_attributes

  private 

  def downcase_attributes
    self.username = username.downcase
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  around_action :switch_locale
  include Pagy::Backend

  def switch_locale(&action)
    I18n.with_locale(locale_from_header, &action)
  end
  
  private 

  def locale_from_header
    request.env['HTTP_ACCEPT_LANGUAGE']&.scan(/^[a-z]{2}/)&.first
  end
end

app/controllers/authentication/users_controller.rb
class Authentication::UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user=User.new(user_params)

    if @user.save
      redirect_to products_path,notice: t('.create')
    else
       render :new,status: :unprocessable_entity
    end

  end

  def user_params
     params.require(:user).permit(:email,:username,:password)
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  # GET /categories or /categories.json
  def index
    @categories = Category.all.order(name: :asc)
  end

  # GET /categories/1 or /categories/1.json

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
    category
  end

  # POST /categories or /categories.json
  def create
    @category = Category.new(category_params)
    puts category_params
    respond_to do |format|
      if category.save
        format.html { redirect_to categories_path, notice: "Category was successfully created." }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1 or /categories/1.json
  def update
    respond_to do |format|
      if category.update(category_params)
        format.html { redirect_to categories_path, notice: t('.updated') }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1 or /categories/1.json
  def destroy
    category.destroy

    respond_to do |format|
      format.html { redirect_to categories_url, notice: t('.destroyed') }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def category
      @category ||= Category.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def category_params
      params.require(:category).permit(:name)
    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @categories=Category.order(name: :asc).load_async
   # @products=Product.all.with_attached_photo.load_async

   # if params[:category_id]
   #   @products = @products.where(category_id: params[:category_id])
   # end
   # if params[:min_price].present?
   #   @products = @products.where("price >= ?", params[:min_price])
   # end

   # if params[:max_price].present?
   #   @products = @products.where("price <= ?", params[:max_price])
   # end

    
    #if params[:query_text].present?
    #  @products = Product.search_full_text(params[:query_text])
    #end

   #order_by={newest: "created_at DESC",expensive: "price DESC",cheapest: "price ASC"}.fetch(params[:order_by]&.to_sym,"Created_at DESC")
   #  puts order_by+"--------------------------------------------------------------------------------------------"
   # @products=@products.order(order_by).load_async

    @pagy, @products = pagy_countless(FindProducts.new.call(product_params_index).load_async, items: 12)


  end
  def show
    product
  end

  def new
    @product=Product.new
  end
  def create
    @product=Product.new(product_params)
    if @product.save
      redirect_to products_path,notice: t('.created'),status: :see_other
    else
       render :new,status: :unprocessable_entity 
    end
  end
  def product_params
    params.require(:product).permit(:title,:description,:price,:photo,:category_id)
  end

  def edit
    product
  end

  def update
    if product.update(product_params)
      puts 'funciona el redireccionamiento-----------------------------------------------------------'
      redirect_to products_path, notice: t('.updated')
    else
      render :edit, status: :unproceassable_entity
    end
  end

  def destroy
    puts 'Se esta eliminando _________________---------------------------------------------_________________________________----------------a'
    product.destroy
    puts 'Se esta eliminando _________________---------------------------------------------_________________________________----------------a'
    redirect_to products_path, notice: t('.deleted')
  end

  def product_params_index
    params.permit(:category_id,:min_price,:max_price,:query_text,:order_by)
  end

  def product
    puts 'esta pasando en el controller---------------'
    puts 'este es el params id'+Product.find(params[:id]).title
    @product=Product.find(params[:id])
    puts 'este es el product '+@product.price
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  include Pagy::Frontend
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/authentication/users/new.html.erb
<%= form_with(model: @user) do |form| %>
  <%= @user.errors.full_messages.each do |error|%>
         <%=error%>
         <%end%>
  <div>
    <%= form.label :email  %>
    <%= form.email_field :email %>
  </div>
  <div>
    <%= form.label :username  %>
    <%= form.text_field :username %>
  </div>


  <div>
    <%= form.label :password  %>
    <%= form.password_field :password %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/categories/_category.html.erb
<div id="<%= dom_id category %>">
  <%= category.name%>
  <%= link_to t('.edit'), edit_category_path(category)%>
  <%= link_to t('.delete'), category_path(category), data: {
    turbo_method: :delete,
    turbo_confirm: t('common.confirm')
  } %>
</div>

app/views/categories/_form.html.erb
<%= form_with(model: category) do |form| %>
  <%= @category.errors.full_messages.each do |error|%>
         <%=error%>
         <%end%>
  <div>
    <%= form.label :name  %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1><%=t('.title')%></h1>

<%= render "form", category: @category %>


<div>
  <%= link_to t('common.back'), categories_path %>
</div>

app/views/categories/index.html.erb
<p style="color: green"><%= notice %></p>

<h1><%=t('.title')%></h1>

<%= render  partial: 'category', collection: @categories %>
<%= link_to t('.new'), new_category_path %>

app/views/categories/new.html.erb
<h1><%= t('.title')%></h1>

<%= render "form", category: @category %>


<div>
  <%= link_to t('common.back'), categories_path %>
</div>

app/views/categories/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @category %>

<div>
  <%= link_to "Edit this category", edit_category_path(@category) %> |
  <%= link_to "Back to categories", categories_path %>

  <%= button_to "Destroy this category", @category, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Merca2</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%=notice%>
    <%notice%>
    <%= render 'shared/header'%>
    <%= yield %>
  </body>
</html>

app/views/products/_category.html.erb
<%= link_to products_path(category_id: category.id) do%>
  <%= category.name %>
<%end%>

app/views/products/_form.html.erb
<%= form_with model: @product do |form|%>
  <%= @product.errors.full_messages.each do |error|%>
    <%=error%>
  <%end%>
  <div>
    <%= form.label :title%>
    <%= form.text_field :title%>
  </div>

  <div>
    <%= form.label :description%>
    <%= form.text_area :description%>
  </div>

  <div>
  <%= form.label :price%>
    <%= form.number_field :price%>
  </div>
  <div>
  <%= form.label :category %>
  <%= form.collection_select :category_id, Category.all.order(name: :asc), :id, :name %>
  </div>
  <div>
  <%= form.label :photo%>
    <%= form.file_field :photo%>
  </div>
  <%= form.submit%>
<%end%>

app/views/products/_product.html.erb
<%= link_to product_path(product.id), class: 'product'  do %>
    <h1><%=product.title%></h1>
    <%= image_tag product.photo, width: 100 if product.photo.attached?%> 
    <br>
    <br>
    <span><%=product.description%></span>
<%end%>

app/views/products/edit.html.erb
<h1><%= t('.title')%></h1>
<%=render 'form'%>

app/views/products/index.html.erb
<%= turbo_frame_tag 'home' do%>
<%=notice%>
<h1><%= t('.title') %> </h1>

<%= form_with url: products_path, method: :get do |form|%>
  <%= form.text_field :query_text,placeholder: t('.query_text'), onChange: 'this.form.requestSubmit()',value: params[:query_text]%>
  <br>
  <%= form.number_field :max_price,placeholder: t('.max_price'), onChange: 'this.form.requestSubmit()',value: params[:max_price]%>
  <%= form.number_field :min_price,placeholder: t('.min_price'), onChange: 'this.form.requestSubmit()',value: params[:min_price]%>
<%= form.select :order_by,options_for_select(Product::ORDER_BY.keys.map{|order| [t(".#{order}"),order]},params[:order_by]),{},{onChange: 'this.form.requestSubmit()'}%>
<%end%>
<%= render partial: 'category', collection: @categories %>
<%= turbo_frame_tag "products-#{@pagy.page}", class: 'products' do %>
  <%= render partial: 'product', collection: @products %>
  <%= turbo_frame_tag "products-#{@pagy.next}",class: 'products',src: pagy_url_for(@pagy,@pagy.next), loading: :lazy %> 
  <%end%>
  <%end%>

app/views/products/new.html.erb
<h1><%= t('.title') %></h1>
<%=render 'form'%>

app/views/products/show.html.erb
<h1><%=@product.title%> </h1>
<%= image_tag @product.photo, width: 200 if @product.photo.attached?%>

<h2><%=@product.description%> </h2>


<span><%=@product.price%> </span>
<%= link_to t('.action1'), edit_product_path(@product)%>
<%= link_to t('.action2'), product_path(@product), data: {
turbo_method: :delete,
turbo_confirm: t('.confirm')
}%>

app/views/shared/_header.html.erb
<%= link_to  products_path do %>
<h1 class="text-red-400 hover:text-red-400 ">Merca2 </h1>
<h1 class="text-green-400 ">prueba </h1>
<%end%>
<%= link_to 'Subir producto', new_product_path %>
<%= link_to t('.categories'), categories_path %>